"""add address column

Revision ID: 66afdd06de13
Revises: 9f34be41fd2f
Create Date: 2025-06-27 17:32:29.123685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66afdd06de13'
down_revision: Union[str, Sequence[str], None] = '9f34be41fd2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shipment', sa.Column('address', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shipment', 'address')
    # ### end Alembic commands ###
